# Generated by Django 6.0.5 on 2026-06-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_rename_name_producto_nombre_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_costo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
