# Generated by Django 6.0.5 on 2026-06-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_producto_precio_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_proveedor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
