# Generated by Django 6.0.5 on 2026-06-23 02:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_alter_producto_id_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Producto'),
        ),
    ]
