# Generated by Django 6.0.5 on 2026-08-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_categoria_alter_producto_options_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='producto',
            name='talle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
