# Generated by Django 6.0.5 on 2026-08-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_producto_color_producto_talle'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE producto
                        ALTER COLUMN talle TYPE jsonb
                        USING CASE
                            WHEN talle IS NULL THEN '[]'::jsonb
                            ELSE jsonb_build_array(talle)
                        END;
                        ALTER TABLE producto
                        ALTER COLUMN talle SET NOT NULL;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='producto',
                    name='talle',
                    field=models.JSONField(blank=True, default=list),
                ),
            ],
        ),
    ]
