# Generated by Django 6.0.5 on 2026-09-11

import django.db.models.deletion
from django.core.management.color import no_style
from django.db import migrations, models


def crear_proveedores_existentes(apps, schema_editor):
    Producto = apps.get_model('producto', 'Producto')
    Proveedor = apps.get_model('producto', 'Proveedor')

    ids_proveedores = (
        Producto.objects.exclude(id_proveedor__isnull=True)
        .values_list('id_proveedor', flat=True)
        .distinct()
    )
    Proveedor.objects.bulk_create(
        [
            Proveedor(
                id=id_proveedor,
                nombre=f'Proveedor migrado {id_proveedor}',
                calle_nombre='Sin especificar',
                calle_numero=0,
                localidad='Sin especificar',
            )
            for id_proveedor in ids_proveedores
        ]
    )

    # Los IDs se insertan explícitamente; se actualiza la secuencia para que
    # el siguiente proveedor creado desde el administrador no repita uno.
    statements = schema_editor.connection.ops.sequence_reset_sql(
        no_style(),
        [Proveedor],
    )
    with schema_editor.connection.cursor() as cursor:
        for statement in statements:
            cursor.execute(statement)


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_alter_producto_talle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('calle_nombre', models.CharField(max_length=100)),
                ('calle_numero', models.IntegerField()),
                ('localidad', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
            },
        ),
        migrations.RunPython(
            crear_proveedores_existentes,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_proveedor',
            field=models.ForeignKey(
                blank=True,
                db_column='id_proveedor',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='productos',
                to='producto.proveedor',
                verbose_name='Proveedor',
            ),
        ),
    ]
