# Generated by Django 6.0.5 on 2026-09-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0013_lineapedido_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoGeneral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
            ],
            options={
                'verbose_name': 'Pedido general',
                'verbose_name_plural': 'Pedidos generales',
                'db_table': 'pedido',
                'ordering': ['-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'abierto')), fields=('estado',), name='pedido_unico_abierto'), models.CheckConstraint(condition=models.Q(('estado__in', ['abierto', 'cerrado'])), name='pedido_estado_valido'), models.CheckConstraint(condition=models.Q(('descripcion', ''), _negated=True), name='pedido_descripcion_no_vacia')],
            },
        ),
    ]
